### PR TITLE
Allow to resize the left & right panes

### PR DESCRIPTION
**Pull request by ghost**
## What does it do?
Allows to resize the left & right panes

## Why the change?
[issue #27 ](https://github.com/Leandros/cpp-tour/issues/27)

## How can this be tested?
drag'n'drop

## Where to start code review?
src/js/UI.js

## Relevant tickets?
[issue #27 ](https://github.com/Leandros/cpp-tour/issues/27)

## Questions?
<Ask us anything!>

### CODE REVIEW

**Review by Leandros — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Should I close commit or you close it usually?

**Comment by Leandros** [comment]
I'll close and merge it.

**Comment by ghost** [comment]
Okay, thank you.

**Comment by Leandros** [comment]
Merged! cb0ce06

**Pull request closed without merging**
