### PR TITLE
Initial layout design

### PR DESCRIPTION
**Pull request by DoumanAsh**
1. Use CodeMirror for editor.
2. Sidebar is strictly controlled by user.
3. Flexible layout that automatically handles sizes through flex.

[Sidebar](https://i.imgur.com/OAgsfb5.png)
[Sidebar closed](https://i.imgur.com/3lv1gHm.png)

### CODE REVIEW

**Comment by Leandros** [comment]
So far, so good! Great work!

I've got only a few minor improvements:

- Sidebar should slide over the content, not pushing it to the right.
- Sidebar should be a lot wider.
- When reducing browser width, the input field should move below the content. Making it usable on thin / mobile devices.
- There should be an always visible header, where we can put the title of the page and a link to the github repository.

**Comment by DoumanAsh** [comment]
>Sidebar should slide over the content, not pushing it to the right.

Not sure I understand: Do you want user to drag sidebar?
Currently he needs to push on slider with `>`/`'<`

*UPD*: Ah you mean you'd like sidebar to be shadow over content(fixed position with z-index).
To be honest I don't like that idea since sidebar is utility that should not overshadow content itself (i.e. user might want to go around looking for particular content)

>When reducing browser width, the input field should move below the content.

By input field do you mean code editor?

>There should be an always visible header, where we can put the title of the page and a link to the github repository.

Header like that(marked red) https://i.imgur.com/1Ccmc0O.png ?

**Comment by Leandros** [comment]
1. The sidebar is utility, exactly like you said. It shadows over the content, you can select a lesson, and it closes again, brining you to the selected lesson. Example: https://appico.com/ Makes a lot more sense than the current implementation.

2. Yes.

3. Yes.

**Comment by DoumanAsh** [comment]
Update. Please take a look at how it looks on various screens:

* [Mobile](https://i.imgur.com/7JpQCSf.png)
* [Kindle](https://i.imgur.com/XNyG7yw.png)
* [Laptop with small screen](https://i.imgur.com/rqAzlJF.png)
* [HD screen](https://i.imgur.com/OKFsYAN.png)

Sidebar height depends on screen's width

Editor changes its location on 960px

**Review by Leandros — APPROVED** [review]

**Comment by Leandros** [comment]
Merged. (Github does not recognize, due to rebase)

**Pull request closed without merging**
